// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr6U9AeObXolpy-Y4n4lTtyRfAKBBQFRA',
    appId: '1:972915612797:web:3b0318dceb75c25af5e514',
    messagingSenderId: '972915612797',
    projectId: 'jio-fashion-hack',
    authDomain: 'jio-fashion-hack.firebaseapp.com',
    storageBucket: 'jio-fashion-hack.appspot.com',
    measurementId: 'G-H3T25LNQDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXDFENqcW3emmsqs9YbXDka6u_kn6l9ic',
    appId: '1:972915612797:android:6862fe0cfb3018c3f5e514',
    messagingSenderId: '972915612797',
    projectId: 'jio-fashion-hack',
    storageBucket: 'jio-fashion-hack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtj70_Nz0vmkSkOxZ163IvE2Thh4C2inU',
    appId: '1:972915612797:ios:ab72f9ad458296f6f5e514',
    messagingSenderId: '972915612797',
    projectId: 'jio-fashion-hack',
    storageBucket: 'jio-fashion-hack.appspot.com',
    iosClientId: '972915612797-0odtpra7t4ljehi5a6tg5lg7buus01f8.apps.googleusercontent.com',
    iosBundleId: 'live.neophyte.jioFashionHack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtj70_Nz0vmkSkOxZ163IvE2Thh4C2inU',
    appId: '1:972915612797:ios:ab72f9ad458296f6f5e514',
    messagingSenderId: '972915612797',
    projectId: 'jio-fashion-hack',
    storageBucket: 'jio-fashion-hack.appspot.com',
    iosClientId: '972915612797-0odtpra7t4ljehi5a6tg5lg7buus01f8.apps.googleusercontent.com',
    iosBundleId: 'live.neophyte.jioFashionHack',
  );
}
